In [1]:
!pip install torch torchvision

     ---------------------------------------- 1.1/1.1 MB 3.7 MB/s eta 0:00:00
     -------------------------------------- 162.6/162.6 MB 5.9 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 1.12.1
    Uninstalling torch-1.12.1:
      Successfully uninstalled torch-1.12.1


In [3]:
import torch
import torchvision
import torchvision.transforms as T

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from torch.autograd import Variable

import torch.nn.functional as F
import torchvision.datasets as dset
from torch.utils.data import sampler
from torch.utils.data import DataLoader

from torch import nn 
from torch import optim

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

In [62]:
a = torch.FloatTensor(3,4)
b = torch.FloatTensor(60)
c = b.view(3,4,5)

In [63]:
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [64]:
b

tensor([-1.0636e-06,  4.5911e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00,
        -1.0885e-06,  4.5911e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,         nan,         nan,  1.4013e-45,  0.0000e+00,
         2.8026e-45,  0.0000e+00, -3.5970e+05,  4.5911e-41,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,         nan,  0.0000e+00])

In [65]:
c

tensor([[[-1.0636e-06,  4.5911e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00],
         [-1.0885e-06,  4.5911e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,         nan,         nan,  1.4013e-45,  0.0000e+00]],

        [[ 2.8026e-45,  0.0000e+00, -3.5970e+05,  4.5911e-41,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,         nan,  0.0000e+00]]])

In [3]:
# Выведите его форму (shape)

In [67]:
print(a.shape, b.shape)

torch.Size([3, 4]) torch.Size([60])


In [4]:
# Приведите его к форме 6 X 10

In [71]:
a, b = torch.zeros(6,10), torch.zeros(60)
c.view_as(c)

tensor([[[-1.0636e-06,  4.5911e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00],
         [-1.0885e-06,  4.5911e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,         nan,         nan,  1.4013e-45,  0.0000e+00]],

        [[ 2.8026e-45,  0.0000e+00, -3.5970e+05,  4.5911e-41,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,         nan,  0.0000e+00]]])

In [73]:
print(a.shape, b.shape)

torch.Size([6, 10]) torch.Size([60])


In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [82]:
x = torch.FloatTensor([1, 4, 2, 2, 1])

In [84]:
c @ x

tensor([[-1.0636e-06,  4.2039e-44, -1.0885e-06,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,         nan],
        [-7.1939e+05,  0.0000e+00,  0.0000e+00,         nan]])

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [94]:
с = torch.FloatTensor([[6,10,60], [60,100,600], [600,1000,6000]])
c = torch.FloatTensor([[-6,-10,-60], [-60,-100,-600], [600,1000,6000]])

In [95]:
c @ с

tensor([[  -36636.,   -61060.,  -366360.],
        [ -366360.,  -610600., -3663600.],
        [ 3663600.,  6106000., 36636000.]])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [ ]:
y = x**3 + z - 75t

In [111]:
x=torch.tensor(1, requires_grad=True) 
z=torch.tensor(0.5, requires_grad=True) 
t=torch.tensor(2, requires_grad=True) 
y = x**3 + z - 75**t
y.backward() 
x.grad 
z.grad 
t.grad

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [104]:
print(x.grad)

None


In [8]:
# Создайте единичный тензор размера 5x6

In [55]:
p = torch.FloatTensor(range(5*6)).view(5,6)

In [56]:
p

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28., 29.]])

In [9]:
# Переведите его в формат numpy

In [57]:
p = p.numpy()
print("P :\n%s\n" % p)
print("P размеры : %s\n" % (p.shape,))
print("P тип : %s\n" % (type(p)))
# print("Добавим 10 :\n%s\n" % (x + 10))
# print("Среднее по строчке :\n%s\n" % (x.mean(axis=-1)))
# print("Среднее по столбцу :\n%s\n" % (x.mean(axis=0)))

P :
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]]

P размеры : (5, 6)

P тип : <class 'numpy.ndarray'>



In [58]:
p = np.random.randint(5, 6)
torch.DoubleTensor()

tensor([], dtype=torch.float64)

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [46]:
y = x**w1 - 2 * x**2 + 5
y.backward(torch.ones(3))

NameError: name 'w1' is not defined

In [47]:
x = np.arange(9).reshape(3, 3)

print("X :\n%s\n" % x)
print("X размеры : %s\n" % (x.shape,))
print("X тип : %s\n" % (type(x)))
# print("Добавим 10 :\n%s\n" % (x + 10))
# print("Среднее по строчке :\n%s\n" % (x.mean(axis=-1)))
# print("Среднее по столбцу :\n%s\n" % (x.mean(axis=0)))

X :
[[0 1 2]
 [3 4 5]
 [6 7 8]]

X размеры : (3, 3)

X тип : <class 'numpy.ndarray'>



In [5]:
def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("X количество измерений:\n%s\n" % tensor.dim())
    print("X размеры : ",  tensor.size())
    print("X тип : %s\n" % (tensor.type()))
#     print("Добавим 10 :\n%s\n" % (tensor + 10))
#     print("Среднее по строчке :\n%s\n" % (tensor.mean(axis=-1)))
#     print("Среднее по столбцу :\n%s\n" % (tensor.mean(axis=0)))

In [6]:
# y = np.arange(9).reshape(3, 3).astype(float)
# x = torch.tensor(y)  
# x = torch.DoubleTensor(3, 3, 3)
x = torch.LongTensor([[1.0, 2.0],[2.0,3.0]])  

<ipython-input-6-7514132001c6>:4: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  x = torch.LongTensor([[1.0, 2.0],[2.0,3.0]])


In [7]:
print_tens_info(x)

X :
tensor([[1, 2],
        [2, 3]])

X количество измерений:
2

X размеры :  torch.Size([2, 2])
X тип : torch.LongTensor



In [11]:
x = torch.arange(9).view(3,3) 
x = torch.arange(0,9).view(3,3).type(torch.float32)
# y = np.arange(9).reshape(3, 3).astype(float)

In [12]:
x = torch.arange(9).view(3,3) 
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [13]:
x = x.numpy()
print("X :\n%s\n" % x)
print("X размеры : %s\n" % (x.shape,))
print("X тип : %s\n" % (type(x)))
# print("Добавим 10 :\n%s\n" % (x + 10))
# print("Среднее по строчке :\n%s\n" % (x.mean(axis=-1)))
# print("Среднее по столбцу :\n%s\n" % (x.mean(axis=0)))

X :
[[0 1 2]
 [3 4 5]
 [6 7 8]]

X размеры : (3, 3)

X тип : <class 'numpy.ndarray'>



In [14]:
x = np.random.randint(2, 3)
torch.DoubleTensor(x)

tensor([0., 0.], dtype=torch.float64)

In [15]:
torch.ones(3)

tensor([1., 1., 1.])

In [16]:
x = Variable(torch.ones(3), requires_grad = True)

In [17]:
print_tens_info(x)

X :
tensor([1., 1., 1.], requires_grad=True)

X количество измерений:
1

X размеры :  torch.Size([3])
X тип : torch.FloatTensor



In [18]:
print(x.grad)

None


In [19]:
z = (x * x) + 5.0 * x #задание - посчитать производную ручками

In [20]:
y = x**2 + 5*x
y.backward(torch.ones(3))

In [21]:
z.backward(torch.ones(3))

In [22]:
print(x.grad)

tensor([14., 14., 14.])


In [23]:
linear = nn.Linear(2, 2)

In [24]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.1886,  0.6296],
        [-0.4037, -0.2432]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.6715, -0.4752], requires_grad=True)


In [25]:
linear(torch.FloatTensor([2, 2]))

tensor([ 2.3078, -1.7690], grad_fn=<AddBackward0>)

In [26]:
torch.matmul(linear.weight, torch.FloatTensor([2, 2])) + linear.bias

tensor([ 2.3078, -1.7690], grad_fn=<AddBackward0>)

In [27]:
criterion = nn.MSELoss()

In [28]:
optimizer = torch.optim.SGD([linear.weight], lr=0.01)

In [29]:
x = Variable(torch.randn(2), requires_grad = True)
y = Variable(torch.randn(2), requires_grad = False)

In [30]:
optimizer.zero_grad()
pred = linear(x)
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  2.9091882705688477


In [31]:
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  None
dL/db:  None


In [33]:
loss.backward()

In [32]:
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  None
dL/db:  None


In [34]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.1886,  0.6296],
        [-0.4037, -0.2432]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.6715, -0.4752], requires_grad=True)


In [35]:
optimizer.step()

In [36]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.1715,  0.6229],
        [-0.3746, -0.2319]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.6715, -0.4752], requires_grad=True)


In [37]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [38]:
torch.randn(10, 10, device=device)

tensor([[ 0.5402,  1.9402,  0.2072, -1.6086,  0.4997, -0.6083,  0.6094,  0.0532,
          0.5031,  0.5953],
        [ 0.1226, -0.1538,  1.0389,  0.1399,  1.2882, -0.1059, -0.0937, -0.3009,
         -1.0509, -1.0525],
        [-0.4390, -0.3103, -0.6171, -0.1349,  0.7878, -0.8279,  0.3187,  0.8238,
         -0.9060, -1.5709],
        [-0.2116, -0.9403, -0.1995, -2.2547,  0.2998,  0.7782,  0.7170, -0.7115,
          1.3045, -0.8328],
        [ 0.3336,  0.7648,  2.1935,  1.5698, -0.8422,  0.2504,  0.4864,  0.0124,
          0.5042,  1.1664],
        [-0.3042, -1.7375,  0.0683, -0.8999, -1.1135, -2.0793,  2.2277, -2.0076,
         -1.4010,  0.6558],
        [-1.0046,  0.5613,  0.2059,  1.4612,  0.4384,  0.9506, -0.6905,  0.2456,
          0.6002, -0.0243],
        [ 0.9204,  0.2822, -0.5218, -0.5786, -0.4466,  0.3669, -0.5481,  2.8992,
         -0.4904, -1.2630],
        [-0.0583, -0.3446,  0.6976,  0.3209,  0.1277,  2.2352,  0.8088,  0.5464,
          0.7386, -1.4031],
        [-0.1148, -

In [39]:
net.to(device)

NameError: name 'net' is not defined